name: 'ontrack-graphql'
description: 'GitHub action to interact with the Ontrack GraphQL API'
author: 'Damien Coraboeuf'
inputs:
  query:
    required: true
    description: 'GraphQL Query or Mutation'
  variables:
    required: false
    description: 'GraphQL variables (map)'
outputs:
  data:
    description: 'GraphQL data node returned by the query or mutation. All errors will have already been processed.'
runs:
  using: 'node12'
  main: 'dist/index.js'
