name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  ONTRACK_URL: ${{ secrets.ONTRACK_URL }}
  ONTRACK_TOKEN: ${{ secrets.ONTRACK_TOKEN }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nemerosa/ontrack-github-action-init@v0
      - name: Get project list
        uses: ./
        with:
          query: |
            query ProjectList {
              projects {
                name
              }
            }
      - name: Get project by name
        uses: ./
        with:
          query: |
            query ProjectByName($name: String!) {
              projects(name: $name) {
                name
              }
            }
          variables: |
            {
              "name": "ontrack"
            }
      - name: Creates or get the current project
        uses: ./
        with:
          query: |
            mutation ProjectSetup($name: String!) {
              createProjectOrGet(name: $name) {
                project {
                  id
                }
              }
            }
